version: '3.3'

services:
    rabbitmq:
      image: rabbitmq:management
      container_name: my-rabbit
      hostname: my-rabbit
      ports:
        - "5672:5672"
        - "15672:15672"
      restart: always
    db:
      image: mysql:latest
      container_name: mysql-db
      environment:
        - MYSQL_ROOT_PASSWORD=spring
      ports:
        - "3306:3306"
      restart: always
    phpmyadmin:
       image: phpmyadmin/phpmyadmin
       container_name: pma
       depends_on:
         - db
       environment:
         PMA_HOST: db
         PMA_PORT: 3306
         PMA_ARBITRARY: 1
       restart: always
       ports:
         - 8081:80
    technicianapp:
      image: technician-app
      container_name: technician-app
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      restart: always
      depends_on:
        - db
        - rabbitmq
      restart: always